"""updated_at to img_cache

Revision ID: 8ceb2e596a39
Revises: b358f432d5ae
Create Date: 2026-03-25 14:41:37.049553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ceb2e596a39'
down_revision: Union[str, Sequence[str], None] = 'b358f432d5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_cache', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
