"""service enums

Revision ID: b358f432d5ae
Revises: 7415b1e6c042
Create Date: 2026-03-25 14:40:13.869418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b358f432d5ae'
down_revision: Union[str, Sequence[str], None] = '7415b1e6c042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('results', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('searched_providers', sa.JSON(), nullable=False))
        batch_op.drop_column('sources')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sources', sqlite.JSON(), nullable=False))
        batch_op.drop_column('searched_providers')
        batch_op.drop_column('results')

    # ### end Alembic commands ###
